#!/usr/bin/env python
# _____         _           _       _     _
#|  _  |___ ___| |_ ___ ___| |_ ___|_|___| |_ ___
#|   __|  _| . |  _| . |   |  _|  _| |  _| '_|_ -|
#|__|  |_| |___|_| |___|_|_|_| |_| |_|___|_,_|___|
# A simple wrapper that makes it slightly less painful to use winetricks with Proton prefixes.
# Script by Sirmentio, Copyright 2018, Licensed under the GPLv3!

import os, sys

def eprint(*args, prefix=None, **kwargs):
    """Prints to sys.stderr, prefixed with prefix, or '[ERROR!] ' if prefix is not given."""
    kwargs['file'] = sys.stderr
    print(prefix or '[ERROR!] ', **dict(kwargs, end=''))
    print(*args, **kwargs)

# Prerequisite check
prereq_fail = False

# Check if $STEAM_DIR is a valid environment variable, otherwise use the default.
steam_dir = os.environ.get('STEAM_DIR')
if not steam_dir:
    steam_dir = os.path.join(os.environ.get('HOME'), '.steam')
    print('[INFO  ] Dunno where Steam is, checking ' + steam_dir + '. To avoid this consider setting $STEAM_DIR')
else:
    print('[INFO  ] Current Steam directory is... ' + steam_dir)

# Find winetricks
try:
    import shutil
    winetricks_path = shutil.which('winetricks')
except:
    winetricks_path = None
    for path in os.environ['PATH'].split(os.pathsep):
        path = os.path.join(path, 'winetricks')
        if os.access(path, os.X_OK):
            winetricks_path = path
            break

prereq_fail = True
if not winetricks_path or not os.path.exists(winetricks_path):
    eprint("Winetricks isn't installed, please install winetricks in order to use this script!")
elif not os.path.isdir(os.path.join(steam_dir, 'steamapps', 'compatdata')):
    eprint('Proton prefix folder not found, do you have the Steam beta installed? Is $STEAM_DIR set correctly?')
else:
    prereq_fail = False

# If one or more checks fail, don't do anything in the script.
if prereq_fail:
    eprint('Sorry, one or more errors prevents this script from being used, check the console for details...', prefix='[FATAL ] ')
    sys.exit(-1)
# If nothing has failed, move on.

# Argument 1 is the steam game ID, so add it as a variable here.
game_id = sys.argv[1]
# Check if the current id is valid.
prefix_dir = os.path.join(steam_dir, 'steamapps', 'compatdata', game_id)
if not os.path.isdir(prefix_dir):
    eprint('You don\'t seem to have a game with that ID, is it installed and Proton compatible? You can usually get the game ID via the store page URL.', prefix='[FATAL ] ')
    sys.exit(-1)
# Finally, let's run winetricks with the specified prefix folder.
print('[INFO  ] Prefix directory is at ' + prefix_dir)
os.environ['WINEPREFIX'] = prefix_dir

sys.stdout.flush()
os.execv(winetricks_path, [winetricks_path] + sys.argv[2:])
